### ISSUE TITLE
`ordered` should not have a newline after "order"

### ISSUE THREAD

**Issue by the-mikedavis** [tonyvanriet/lunch-bot#7]
<img width="237" alt="Screen Shot 2019-07-11 at 8 40 02 AM" src="https://user-images.githubusercontent.com/21230295/61055610-878cb900-a3b7-11e9-8199-a94ea6b63f96.png">

**Comment by the-mikedavis** [comment]
On a similar note, these could be numbered to make it easier to use #6

**Comment by the-mikedavis** [comment]
Also it should be "Your latest orders **from** {{ restaurant }}"

**Comment by the-mikedavis** [comment]
Ideal example usage:

> Your latest orders from SweetGreen
> 1. `chicken tostada bowl`
> 1. `chicken tostada bowl`
> 1. `chicken tostada bowl`

**Comment by tonyvanriet** [comment]
@the-mikedavis why shouldn't `ordered` have a newline?
